spring.application.name=auth-api
app.cors.allowed-origins=http://localhost:3000
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000


#postgres
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

data-api.url=${DATA_API_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

internal.secret=${INTERNAL_TOKEN}